// Code generated by "enumer -type RoleType -json"; DO NOT EDIT.

package enum

import (
	"encoding/json"
	"fmt"
)

const _RoleTypeName = "RoleUnknownRoleUserRoleAdmin"

var _RoleTypeIndex = [...]uint8{0, 11, 19, 28}

func (i RoleType) String() string {
	i -= -1
	if i < 0 || i >= RoleType(len(_RoleTypeIndex)-1) {
		return fmt.Sprintf("RoleType(%d)", i+-1)
	}
	return _RoleTypeName[_RoleTypeIndex[i]:_RoleTypeIndex[i+1]]
}

var _RoleTypeValues = []RoleType{-1, 0, 1}

var _RoleTypeNameToValueMap = map[string]RoleType{
	_RoleTypeName[0:11]:  -1,
	_RoleTypeName[11:19]: 0,
	_RoleTypeName[19:28]: 1,
}

// RoleTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleTypeString(s string) (RoleType, error) {
	if val, ok := _RoleTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to RoleType values", s)
}

// RoleTypeValues returns all values of the enum
func RoleTypeValues() []RoleType {
	return _RoleTypeValues
}

// IsARoleType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i RoleType) IsARoleType() bool {
	for _, v := range _RoleTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for RoleType
func (i RoleType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for RoleType
func (i *RoleType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("RoleType should be a string, got %s", data)
	}

	var err error
	*i, err = RoleTypeString(s)
	return err
}
